services:
  stage-display:
    build: .
    ports:
      - "6767:6767"
    volumes:
      - ./data.json:/app/data.json
      - ./campuses.json:/app/campuses.json
    restart: always
    environment:
      - PORT=6767
